title: Peter Giordano
description: Portfolio Website
show_downloads: false
remote_theme: pages-themes/cayman@v0.2.0
repository: pgnj99/pgnj99.github.io

plugins:
  - jekyll-seo-tag

nav:
  - title: Home
    url: /
  - title: Projects
    url: /projects
  - title: About
    url: /about
